[project]
name = "uv-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.1.5",
    "fastapi>=0.115.8",
    "flask>=3.1.0",
    "mongo>=0.2.0",
    "pytest>=8.3.4",
    "requests>=2.32.3",
]
